translator:
  type: openai #openai
  openai_api_key: YOUR-KEY-GOES-HERE
  openai_base_url: YOUR-OPENAI-BASE-URL
  openai_model_name: gpt-4o-mini

layout:
  type: 'dit'
  device: 'cuda'

ocr:
  type: 'paddle'
  device: 'cuda'

font:
  type: 'simple'